# Generated by Django 2.0.4 on 2018-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_score', models.FloatField(default=0)),
                ('tofel_score', models.FloatField(default=0)),
                ('university_rating', models.FloatField(default=0)),
                ('sop', models.FloatField(default=0)),
                ('lor', models.FloatField(default=0)),
                ('cgpa', models.FloatField(default=0)),
                ('research', models.IntegerField(default=0)),
            ],
        ),
    ]
