# Generated by Django 2.0.4 on 2018-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('datasetLink', models.URLField(blank=True, null=True)),
                ('optionalLink', models.URLField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=100)),
                ('Contact_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
