# Generated by Django 2.0.4 on 2018-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerid', models.FloatField(default=0)),
                ('passengerclass', models.FloatField(default=0)),
                ('age', models.FloatField(default=0)),
                ('siblings', models.IntegerField(default=0)),
                ('parents', models.IntegerField(default=0)),
                ('fare', models.FloatField(default=0.0)),
                ('female', models.IntegerField(default=0)),
                ('male', models.IntegerField(default=0)),
                ('Cherbourg', models.IntegerField(default=0)),
                ('Queenstown', models.IntegerField(default=0)),
                ('Southampton', models.IntegerField(default=0)),
            ],
        ),
    ]
